services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - forecast-service
      - control-service
      - simulation-service
    volumes:
      - ./data:/app/data

  forecast-service:
    build:
      context: .
      dockerfile: docker/forecast.Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  control-service:
    build:
      context: .
      dockerfile: docker/control.Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  simulation-service:
    build:
      context: .
      dockerfile: docker/simulation.Dockerfile
    platform: linux/amd64
    ports:
      - "8003:8003"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - .:/app
    working_dir: /app
    command: python3 apps/simulation_service/test_sinergym.py # Sinergym 테스트를 위함.

  rl-service:
    build:
      context: .
      dockerfile: docker/rl.Dockerfile
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: >
      uv run python -m domain.controllers.rl_agent
      --custom-env
      --total-timesteps 300000
      --run-name exp-default
    profiles:
      - rl

  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard.Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - ./data:/app/data